// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ActivityPhoneCallConfiguration : IEntityTypeConfiguration<ActivityPhoneCall>
    {
        public void Configure(EntityTypeBuilder<ActivityPhoneCall> entity)
        {
            entity.ToTable("ActivityPhoneCall");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false);

            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.Activity)
                .WithMany(p => p.ActivityPhoneCalls)
                .HasForeignKey(d => d.fk_ActivityID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhoneCall_Activity");

            entity.HasOne(d => d.ActivityDirection)
                .WithMany(p => p.ActivityPhoneCalls)
                .HasForeignKey(d => d.fk_ActivityDirectionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhoneCall_ActivityDirection");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActivityPhoneCall> entity);
    }
}
