// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ActivityTaskConfiguration : IEntityTypeConfiguration<ActivityTask>
    {
        public void Configure(EntityTypeBuilder<ActivityTask> entity)
        {
            entity.ToTable("ActivityTask");

            entity.Property(e => e.Description)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.Due).HasColumnType("datetime");

            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.Activity)
                .WithMany(p => p.ActivityTasks)
                .HasForeignKey(d => d.fk_ActivityID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Task_Activity");

            entity.HasOne(d => d.ActivityStatus)
                .WithMany(p => p.ActivityTasks)
                .HasForeignKey(d => d.fk_ActivityStatusID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Task_ActivityStatus");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActivityTask> entity);
    }
}
