// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ActivityEmailConfiguration : IEntityTypeConfiguration<ActivityEmail>
    {
        public void Configure(EntityTypeBuilder<ActivityEmail> entity)
        {
            entity.ToTable("ActivityEmail");

            entity.Property(e => e.BCC)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.Body).IsUnicode(false);

            entity.Property(e => e.CC)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.Recipients)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Sender)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Subject)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.HasOne(d => d.Activity)
                .WithMany(p => p.ActivityEmails)
                .HasForeignKey(d => d.fk_ActivityID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Email_Activity");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActivityEmail> entity);
    }
}
