// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ActionToModuleConfiguration : IEntityTypeConfiguration<ActionToModule>
    {
        public void Configure(EntityTypeBuilder<ActionToModule> entity)
        {
            entity.ToTable("ActionToModule");

            entity.HasOne(d => d.Action)
                .WithMany(p => p.ActionsToModule)
                .HasForeignKey(d => d.fk_ActionID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ActionToModule_Action");

            entity.HasOne(d => d.Module)
                .WithMany(p => p.ActionsToModule)
                .HasForeignKey(d => d.fk_ModuleID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ActionToModule_Module");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ActionToModule> entity);
    }
}
