// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ApiLogConfiguration : IEntityTypeConfiguration<ApiLog>
    {
        public void Configure(EntityTypeBuilder<ApiLog> entity)
        {
            entity.ToTable("ApiLog");

            entity.Property(e => e.IPAddress)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.RequestByURL)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.RequestURL)
                .HasMaxLength(250)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ApiLog> entity);
    }
}
