// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class ProviderLocationConfiguration : IEntityTypeConfiguration<ProviderLocation>
    {
        public void Configure(EntityTypeBuilder<ProviderLocation> entity)
        {
            entity.ToTable("ProviderLocation");

            entity.HasOne(d => d.Location)
                .WithMany(p => p.ProviderLocations)
                .HasForeignKey(d => d.fk_LocationID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderLocation_Location");

            entity.HasOne(d => d.Provider)
                .WithMany(p => p.ProviderLocations)
                .HasForeignKey(d => d.fk_ProviderID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProviderLocation_Provider");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProviderLocation> entity);
    }
}
