// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.ToTable("User");

            entity.Property(e => e.IsPrescriberInstance)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.MiddleName)
               .HasMaxLength(50)
               .IsUnicode(false);

            entity.Property(e => e.Prefix)
               .HasMaxLength(10)
               .IsUnicode(false);

            entity.Property(e => e.IsDeleted)
                .IsRequired()
                .HasDefaultValueSql("(CONVERT([bit],(0)))");

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(2000)
                .IsUnicode(false);

            entity.Property(e => e.PasswordRequestDate).HasColumnType("datetime");

            entity.Property(e => e.PasswordRequestHash)
                .HasMaxLength(1500)
                .IsUnicode(false);

            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.TwoFACode)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.IsDEANumberVerified)
               .HasMaxLength(25)
               .IsUnicode(false);

            entity.Property(e => e.TwoFACodeRequestDate).HasColumnType("datetime");

            entity.HasOne(d => d.UserType)
                .WithMany(p => p.Users)
                .HasForeignKey(d => d.fk_UserTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserType");

            entity.Property(e => e.DEACertificateUrl)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.PrescriberSignatureUrl)
                .HasMaxLength(200)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
