// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HartleyMedical.Domain.Entities;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace HartleyMedical.Infrastructure.Persistence.Configurations
{
    public partial class UserToOrganizationRoleConfiguration : IEntityTypeConfiguration<UserToOrganizationRole>
    {
        public void Configure(EntityTypeBuilder<UserToOrganizationRole> entity)
        {
            entity.ToTable("UserToOrganizationRole");

            entity.HasOne(d => d.Role)
                .WithMany(p => p.UserToOrganizations)
                .HasForeignKey(d => d.fk_RoleID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserToOrganizationRole_Role");

            entity.HasOne(d => d.User)
                .WithMany(p => p.UserToOrganizationRoles)
                .HasForeignKey(d => d.fk_UserID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserToOrganizationRole_User");

            entity.HasOne(d => d.Organization)
                .WithMany(p => p.UserToOrganizations)
                .HasForeignKey(d => d.fk_OrganizationID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserToOrganizationRole_Organization");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserToOrganizationRole> entity);
    }
}
