// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class ActivityDirection
    {
        public ActivityDirection()
        {
            ActivityMessages = new HashSet<ActivityMessage>();
            ActivityPhoneCalls = new HashSet<ActivityPhoneCall>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<ActivityMessage> ActivityMessages { get; set; }
        public virtual ICollection<ActivityPhoneCall> ActivityPhoneCalls { get; set; }
    }
}