// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class Action
    {
        public Action()
        {
            ActionsToModule = new HashSet<ActionToModule>();    
        }

        public int ID { get; set; }
        public string ActionName { get; set; }
        public string Description { get; set; }
        public virtual ICollection<ActionToModule> ActionsToModule { get; set; }
    }
}