// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class AddressType
    {
        public AddressType()
        {
            PatientAddresses = new HashSet<PatientAddress>();
        }

        public int ID { get; set; }
        public string TypeName { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<PatientAddress> PatientAddresses { get; set; }
    }
}