// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class ContactType
    {
        public ContactType()
        {
            PatientContacts = new HashSet<PatientContact>();
        }

        public int ID { get; set; }
        public string Type { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<PatientContact> PatientContacts { get; set; }
    }
}