// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class Diagnosis
    {
        public Diagnosis()
        {
            PatientDiagnoses = new HashSet<PatientDiagnosis>();
        }

        public int ID { get; set; }
        public string ICDCode { get; set; }
        public int fk_ICDCodeTypeID { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }

        public virtual ICDCodeType ICDCodeType { get; set; }
        public virtual ICollection<PatientDiagnosis> PatientDiagnoses { get; set; }
    }
}