// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class Entity
    {
        public Entity()
        {
            Files = new HashSet<File>();
        }

        public int ID { get; set; }
        public string EntityName { get; set; }

        public virtual ICollection<File> Files { get; set; }
    }
}