// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class ExceptionLog : BaseModel
    {
        public int ID { get; set; }
        public string EntityName { get; set; }
        public int EntityID { get; set; }
        public string Method { get; set; }
        public string JSON { get; set; }
        public string RequestUrl { get; set; }
        public string RequestJSON { get; set; }
        public string Exception { get; set; }
    }
}