// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class File
    {
        public int ID { get; set; }
        public int fk_EntityID { get; set; }
        public int RecordID { get; set; }
        public string fileURL { get; set; }
        public string fileType { get; set; }
        public string fileSize { get; set; }
        public int UploadedBy { get; set; }
        public DateTime UploadedDate { get; set; }

        public virtual User UploadedByUser { get; set; }
        public virtual Entity Entity { get; set; }
    }
}