// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class MaritalStatus
    {
        public MaritalStatus()
        {
            Patients = new HashSet<Patient>();
        }

        public int ID { get; set; }
        public string Value { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<Patient> Patients { get; set; }
    }
}