// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class Module
    {
        public Module()
        {
            ActionsToModule = new HashSet<ActionToModule>();
        }

        public int ID { get; set; }
        public string ModuleName { get; set; }

        public virtual ICollection<ActionToModule> ActionsToModule { get; set; }
    }
}