// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class Organization : BaseModel
    {
        public Organization()
        {
            Locations = new HashSet<Location>();
            UserToOrganizations = new HashSet<UserToOrganizationRole>();
        }

        public int ID { get; set; }
        public string FacilityName { get; set; }
        public int fk_OrganizationTypeID { get; set; }
        public string GroupNPI { get; set; }
        public string TaxIdentificationNumber { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }

        public virtual OrganizationType OrganizationType { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<UserToOrganizationRole> UserToOrganizations { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual User ModifiedByUser { get; set; }
    }
}