// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class PatientDiagnosis : BaseModel
    {
        public int ID { get; set; }
        public int fk_PatientID { get; set; }
        public int fk_DiagnosisID { get; set; }
        public string Sequence { get; set; }
        public string ShortDescription { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual User ModifiedByUser { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Patient Patient { get; set; }
    }
}