// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class PatientProvider
    {
        public int ID { get; set; }
        public int fk_PatientID { get; set; }
        public int fk_ProviderTypeID { get; set; }
        public int fk_ProviderID { get; set; }
        public bool Deleted { get; set; }

        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ProviderType ProviderType { get; set; }
    }
}