// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class PayorLevel
    {
        public PayorLevel()
        {
            PatientPayors = new HashSet<PatientPayor>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<PatientPayor> PatientPayors { get; set; }
    }
}