// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class ProviderLocation
    {
        public int ID { get; set; }
        public int fk_ProviderID { get; set; }
        public int fk_LocationID { get; set; }

        public virtual Location Location { get; set; }
        public virtual Provider Provider { get; set; }
    }
}