// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class RolePermission : BaseModel
    {
        public int ID { get; set; }
        public int fk_ActionToModuleID { get; set; }
        public int fk_RoleID { get; set; }
        public bool Active { get; set; }

        public virtual ActionToModule ActionToModule { get; set; }
        public virtual Role Role { get; set; }
    }
}