// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class UserToOrganizationRole
    {
        public int ID { get; set; }
        public int fk_UserID { get; set; }
        public int fk_RoleID { get; set; }
        public int fk_OrganizationID { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual Organization Organization { get; set; }
        
    }
}