// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class User : BaseModel
    {
        public User()
        {
            ActivitiesCreatedByUser = new HashSet<Activity>();
            ActivitiesModifiedByUser = new HashSet<Activity>();
            EmailTemplatesCreatedByUser = new HashSet<EmailTemplate>();
            EmailTemplatesModifiedByUser = new HashSet<EmailTemplate>();
            Files = new HashSet<File>();
            PatientContactsCreatedByUser = new HashSet<PatientContact>();
            PatientContactsModifiedByUser = new HashSet<PatientContact>();
            PatientsCreatedByUser = new HashSet<Patient>();
            PatientsModifiedByUser = new HashSet<Patient>();
            PatientDiagnosisCreatedByUser = new HashSet<PatientDiagnosis>();
            PatientDiagnosisModifiedByUser = new HashSet<PatientDiagnosis>();
            PatientPayorEligibilitiesCreatedByUser = new HashSet<PatientPayorEligibility>();
            PatientPayorEligibilitiesModifiedByUser = new HashSet<PatientPayorEligibility>();
            UserToOrganizationRoles = new HashSet<UserToOrganizationRole>();
            OrganizationsCreatedByUser = new HashSet<Organization>();
            OrganizationsModifiedByUser = new HashSet<Organization>();
            LocationsCreatedByUser = new HashSet<Location>();
            LocationsModifiedByUser = new HashSet<Location>();
            RolesCreatedByUser = new HashSet<Role>();
            RolesModifiedByUser = new HashSet<Role>();
            DEAHistories = new HashSet<DEAHistory>();
            UserToDEAHistories = new HashSet<UserToDEAHistory>();
        }

        public int ID { get; set; }
        public bool IsPrescriberInstance { get; set; }
        public int fk_UserTypeID { get; set; }
        public int fk_BranchID { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public string PasswordRequestHash { get; set; }
        public DateTime? PasswordRequestDate { get; set; }
        public bool IsDeleted { get; set; }
        public string TwoFACode { get; set; }
        public DateTime? TwoFACodeRequestDate { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFAEnabled { get; set; }
        public string DEANumber { get; set; }
        public bool IsDEANumberVerified { get; set; }
        public string DEACertificateUrl { get; set; }
        public string PrescriberSignatureUrl { get; set; }

        public virtual UserType UserType { get; set; }

        public virtual ICollection<DEAHistory> DEAHistories { get; set; }

        public virtual ICollection<UserMedicalInfo> UserMedicalInfos { get; set; }
        public virtual ICollection<Activity> ActivitiesCreatedByUser { get; set; }
        public virtual ICollection<Activity> ActivitiesModifiedByUser { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplatesCreatedByUser { get; set; }
        public virtual ICollection<EmailTemplate> EmailTemplatesModifiedByUser { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<PatientContact> PatientContactsCreatedByUser { get; set; }
        public virtual ICollection<PatientContact> PatientContactsModifiedByUser { get; set; }
        public virtual ICollection<Patient> PatientsCreatedByUser { get; set; }
        public virtual ICollection<Patient> PatientsModifiedByUser { get; set; }
        public virtual ICollection<PatientDiagnosis> PatientDiagnosisCreatedByUser { get; set; }
        public virtual ICollection<PatientDiagnosis> PatientDiagnosisModifiedByUser { get; set; }
        public virtual ICollection<PatientPayorEligibility> PatientPayorEligibilitiesCreatedByUser { get; set; }
        public virtual ICollection<PatientPayorEligibility> PatientPayorEligibilitiesModifiedByUser { get; set; }
        public virtual ICollection<Organization> OrganizationsCreatedByUser { get; set; }
        public virtual ICollection<Organization> OrganizationsModifiedByUser { get; set; }
        public virtual ICollection<Location> LocationsCreatedByUser { get; set; }
        public virtual ICollection<Location> LocationsModifiedByUser { get; set; }
        public virtual ICollection<UserToOrganizationRole> UserToOrganizationRoles { get; set; }
        public virtual ICollection<UserToDEAHistory> UserToDEAHistories { get; set; }
        public virtual ICollection<Role> RolesCreatedByUser { get; set; }
        public virtual ICollection<Role> RolesModifiedByUser { get; set; }
    }
}