// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HartleyMedical.Domain.Entities
{
    public partial class UserType
    {
        public UserType()
        {
            Users = new HashSet<User>();
            Roles = new HashSet<Role>();
        }

        public int ID { get; set; }
        public string Type { get; set; }

        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}