CREATE TABLE [dbo].[Patient] (
    [ID]                   INT              IDENTITY (1, 1) NOT NULL,
    [PatientGUID]          UNIQUEIDENTIFIER NOT NULL,
    [fk_MaritalStatusID]   INT              NULL,
    [fk_GenderID]          INT              NULL,
    [fk_LinkedPatientID]   INT              NULL,
    [fk_LocationID]        INT              NOT NULL,
    [LastName]             VARCHAR (50)     NULL,
    [FirstName]            VARCHAR (50)     NULL,
    [MiddleName]           VARCHAR (50)     NULL,
    [FaxNumber]            VARCHAR (15)     NULL,
    [EmailAddress]         VARCHAR (50)     NULL,
    [MobilePhone]          VARCHAR (15)     NULL,
    [Suffix]               VARCHAR (15)     NULL,
    [DOB]                  DATE             NULL,
    [DOD]                  DATE             NULL,
    [DateOfAdmission]      DATE             NULL,
    [DateOfDischarge]      DATE             NULL,
    [DateOfOnset]          DATE             NULL,
    [StateOfAutoAccident]  VARCHAR (50)     NULL,
    [SSN]                  CHAR (9)         NULL,
    [HoldAcct]             BIT              NULL,
    [Height]               VARCHAR (10)     NULL,
    [Weight]               VARCHAR (10)     NULL,
    [DiscountPct]          INT              NULL,
    [AccountNumber]        VARCHAR (50)     NULL,
    [HIPPASignatureOnFile] BIT              NULL,
    [MobileVerifiedDate]   DATETIME         NULL,
    [EmailVerifiedDate]    DATETIME         NULL,
    [CreatedBy]            INT              NOT NULL,
    [CreatedDate]          DATETIME         NOT NULL,
    [ModifiedBy]           INT              NULL,
    [ModifiedDate]         DATETIME         NULL,
    CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Patient_Gender] FOREIGN KEY ([fk_GenderID]) REFERENCES [dbo].[Gender] ([ID]),
    CONSTRAINT [FK_Patient_Location] FOREIGN KEY ([fk_LocationID]) REFERENCES [dbo].[Location] ([ID]),
    CONSTRAINT [FK_Patient_MaritalStatus] FOREIGN KEY ([fk_MaritalStatusID]) REFERENCES [dbo].[MaritalStatus] ([ID]),
    CONSTRAINT [FK_Patient_Patient] FOREIGN KEY ([fk_LinkedPatientID]) REFERENCES [dbo].[Patient] ([ID]),
    CONSTRAINT [FK_Patient_User] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_Patient_User1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([ID])
);

