CREATE TABLE [dbo].[PatientPayorEligibilityDetail] (
    [EligibilityDetailID]         INT           IDENTITY (1, 1) NOT NULL,
    [fk_PatientPayorEligiblityID] INT           NOT NULL,
    [LastName]                    VARCHAR (50)  NULL,
    [FirstName]                   VARCHAR (50)  NULL,
    [MiddleName]                  VARCHAR (50)  NULL,
    [AddressLine1]                VARCHAR (150) NULL,
    [AddressLine2]                VARCHAR (150) NULL,
    [City]                        VARCHAR (50)  NULL,
    [ZipCode]                     VARCHAR (50)  NULL,
    [Dob]                         DATE          NULL,
    [Relationship]                VARCHAR (50)  NULL,
    [Gender]                      CHAR (1)      NULL,
    [MemberID]                    VARCHAR (50)  NULL,
    [EligibilityBegin]            VARCHAR (50)  NULL,
    [PlanText]                    VARCHAR (50)  NULL,
    [PlanType]                    VARCHAR (50)  NULL,
    [PlanBegin]                   VARCHAR (50)  NULL,
    [PlanNumber]                  VARCHAR (50)  NULL,
    [GroupNumber]                 VARCHAR (50)  NULL,
    [OtherInfo]                   VARCHAR (MAX) NULL,
    [Active]                      BIT           NOT NULL,
    [ReportText]                  VARCHAR (MAX) NULL,
    [Note]                        VARCHAR (MAX) NULL,
    [CreatedDate]                 DATETIME      NOT NULL,
    [RawJsonData]                 VARCHAR (MAX) NULL,
    [fk_StateID]                  INT           NULL,
    CONSTRAINT [PK_PatientPayorEligibilityDetail] PRIMARY KEY CLUSTERED ([EligibilityDetailID] ASC),
    CONSTRAINT [FK_PatientPayorEligibilityDetail_PatientPayorEligibility] FOREIGN KEY ([fk_PatientPayorEligiblityID]) REFERENCES [dbo].[PatientPayorEligibility] ([EligibilityID]),
    CONSTRAINT [FK_PatientPayorEligibilityDetail_State] FOREIGN KEY ([fk_StateID]) REFERENCES [dbo].[State] ([ID])
);

