CREATE TABLE [dbo].[PatientPayorEligibility] (
    [EligibilityID]          INT              IDENTITY (1, 1) NOT NULL,
    [EligibilityGUID]        UNIQUEIDENTIFIER NULL,
    [fk_PatientID]           INT              NULL,
    [fk_PatientPayorID]      INT              NULL,
    [ProviderLastName]       VARCHAR (50)     NULL,
    [ProviderFirstName]      VARCHAR (50)     NULL,
    [ProviderNPI]            VARCHAR (50)     NULL,
    [ProviderPIN]            VARCHAR (50)     NULL,
    [ProviderTaxanomy]       VARCHAR (50)     NULL,
    [VerificationType]       VARCHAR (50)     NULL,
    [SubcriberLastName]      VARCHAR (50)     NULL,
    [SubcriberFirstName]     VARCHAR (50)     NULL,
    [SubcriberMemberID]      VARCHAR (50)     NULL,
    [SubcriberSSN]           VARCHAR (50)     NULL,
    [SubscriberGroupNumber]  VARCHAR (50)     NULL,
    [DependentLastName]      VARCHAR (50)     NULL,
    [DependentFirstName]     VARCHAR (50)     NULL,
    [DependentRelationship]  VARCHAR (50)     NULL,
    [PatientGender]          VARCHAR (50)     NULL,
    [PatientDOB]             VARCHAR (50)     NULL,
    [IssueDate]              VARCHAR (50)     NULL,
    [DateOfServiceFrom]      VARCHAR (50)     NULL,
    [DateOfServiceTo]        VARCHAR (50)     NULL,
    [BatchName]              VARCHAR (50)     NULL,
    [ServiceCodes]           VARCHAR (50)     NULL,
    [Notes]                  VARCHAR (2000)   NULL,
    [Manual]                 BIT              NOT NULL,
    [EligibilityRequestData] VARCHAR (MAX)    NOT NULL,
    [EligiblityRawResponse]  VARCHAR (MAX)    NOT NULL,
    [CreatedBy]              INT              NOT NULL,
    [CreatedDate]            DATETIME         NOT NULL,
    [ModifiedBy]             INT              NULL,
    [ModifiedDate]           DATETIME         NULL,
    CONSTRAINT [PK_PatientPayorEligibility] PRIMARY KEY CLUSTERED ([EligibilityID] ASC),
    CONSTRAINT [FK_PatientPayorEligibility_Patient] FOREIGN KEY ([fk_PatientID]) REFERENCES [dbo].[Patient] ([ID]),
    CONSTRAINT [FK_PatientPayorEligibility_PatientPayor] FOREIGN KEY ([fk_PatientPayorID]) REFERENCES [dbo].[PatientPayor] ([ID]),
    CONSTRAINT [FK_PatientPayorEligibility_User] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_PatientPayorEligibility_User1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([ID])
);

