CREATE TABLE [dbo].[PatientContact] (
    [ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [fk_PatientID]          INT           NOT NULL,
    [fk_ContactTypeID]      INT           NOT NULL,
    [fk_RelationshipTypeID] INT           NOT NULL,
    [FirstName]             VARCHAR (50)  NOT NULL,
    [LastName]              VARCHAR (50)  NOT NULL,
    [Email]                 VARCHAR (100) NULL,
    [PhoneNumber]           VARCHAR (11)  NOT NULL,
    [MobileNumber]          VARCHAR (11)  NOT NULL,
    [FaxNumber]             VARCHAR (11)  NULL,
    [AddressLine1]          VARCHAR (50)  NULL,
    [AddressLine2]          VARCHAR (50)  NULL,
    [City]                  VARCHAR (50)  NULL,
    [PostalCode]            VARCHAR (50)  NULL,
    [Active]                BIT           NOT NULL,
    [CreatedBy]             INT           NOT NULL,
    [CreatedDate]           DATETIME      NOT NULL,
    [ModifiedBy]            INT           NULL,
    [ModifiedDate]          DATETIME2 (7) NULL,
    [fk_StateID]            INT           NULL,
    CONSTRAINT [PK_PatientContact] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PatientContact_ContactType] FOREIGN KEY ([fk_ContactTypeID]) REFERENCES [dbo].[ContactType] ([ID]),
    CONSTRAINT [FK_PatientContact_Patient] FOREIGN KEY ([fk_PatientID]) REFERENCES [dbo].[Patient] ([ID]),
    CONSTRAINT [FK_PatientContact_RelationshipType] FOREIGN KEY ([fk_RelationshipTypeID]) REFERENCES [dbo].[RelationshipType] ([ID]),
    CONSTRAINT [FK_PatientContact_State] FOREIGN KEY ([fk_StateID]) REFERENCES [dbo].[State] ([ID]),
    CONSTRAINT [FK_PatientContact_User] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[User] ([ID]),
    CONSTRAINT [FK_PatientContact_User1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[User] ([ID])
);

