CREATE TABLE [dbo].[Payor] (
    [ID]                      INT              IDENTITY (1, 1) NOT NULL,
    [PayorGUID]               UNIQUEIDENTIFIER NOT NULL,
    [PayorName]               VARCHAR (100)    NOT NULL,
    [Address1]                VARCHAR (50)     NULL,
    [Address2]                VARCHAR (50)     NULL,
    [City]                    VARCHAR (50)     NULL,
    [State]                   CHAR (2)         NULL,
    [PostalCode]              CHAR (10)        NULL,
    [PhoneNumber]             VARCHAR (15)     NULL,
    [FaxNumber]               VARCHAR (15)     NULL,
    [EmailAddress]            VARCHAR (50)     NULL,
    [SiteUrl]                 VARCHAR (100)    NULL,
    [ContactFirstName]        VARCHAR (50)     NULL,
    [ContactMiddleName]       VARCHAR (50)     NULL,
    [ContactLastName]         VARCHAR (50)     NULL,
    [PayPercentage]           TINYINT          NULL,
    [AccountOnHold]           BIT              NULL,
    [GroupName]               VARCHAR (50)     NULL,
    [GroupNumber]             INT              NULL,
    [CompanyName]             VARCHAR (50)     NULL,
    [PlanType]                VARCHAR (50)     NULL,
    [PriceTable]              VARCHAR (50)     NULL,
    [ClaimPercentage]         VARCHAR (50)     NULL,
    [Submission]              VARCHAR (50)     NULL,
    [TaxType]                 VARCHAR (50)     NULL,
    [Pcn]                     VARCHAR (50)     NULL,
    [Bin]                     VARCHAR (50)     NULL,
    [Active]                  BIT              NOT NULL,
    [RawData]                 VARCHAR (MAX)    NULL,
    [CreatedBy]               INT              DEFAULT ((0)) NOT NULL,
    [CreatedDate]             DATETIME2 (7)    DEFAULT ('0001-01-01T00:00:00.0000000') NOT NULL,
    [IsEDIPayer]              BIT              DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [IsSupportingClaims]      BIT              DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [IsSupportingEligibility] BIT              DEFAULT (CONVERT([bit],(0))) NOT NULL,
    [ModifiedBy]              INT               NULL,
    [ModifiedDate]            DATETIME2 (7)     NULL,
    [PayorCode]               VARCHAR (50)     DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_Payor] PRIMARY KEY CLUSTERED ([ID] ASC)
);

