CREATE TABLE [dbo].[Provider] (
    [ID]                  INT              IDENTITY (1, 1) NOT NULL,
    [ProviderHubID]       UNIQUEIDENTIFIER NOT NULL,
    [fk_ParentProviderID] INT              NULL,
    [Title]               VARCHAR (100)    NULL,
    [Suffix]              VARCHAR (15)     NULL,
    [LastName]            VARCHAR (50)     NULL,
    [MiddleName]          VARCHAR (50)     NULL,
    [FirstName]           VARCHAR (50)     NULL,
    [Address1]            VARCHAR (80)     NULL,
    [Address2]            VARCHAR (50)     NULL,
    [City]                VARCHAR (50)     NULL,
    [State]               CHAR (2)         NULL,
    [PostalCode]          CHAR (10)        NULL,
    [EmailAddress]        VARCHAR (50)     NULL,
    [MobilePhone]         VARCHAR (15)     NULL,
    [PhoneNumber]         VARCHAR (15)     NULL,
    [FaxNumber]           VARCHAR (15)     NULL,
    [DoctorGroup]         VARCHAR (MAX)    NULL,
    [UPIN]                CHAR (10)        NULL,
    [MedicalID]           VARCHAR (15)     NULL,
    [DEANumber]           VARCHAR (15)     NULL,
    [DEAExpiryDate]       DATETIME         NULL,
    [LicenseExpiryDate]   DATETIME         NULL,
    [StateMedicaidID]     VARCHAR (30)     NULL,
    [NPINumber]           VARCHAR (80)     NULL,
    [CommercialNumber]    VARCHAR (80)     NULL,
    [TaxonomyCode]        VARCHAR (80)     NULL,
    [Specialty]           VARCHAR (1000)   NULL,
    [IMSRxerID]           VARCHAR (50)     NULL,
    [Location]            VARCHAR (80)     NULL,
    [MarketDecile]        INT              NULL,
    [DegreeDescription]   VARCHAR (1000)   NULL,
    [Note]                TEXT             NULL,
    [Active]              BIT              NOT NULL,
    [CreatedBy]           INT              NOT NULL,
    [CreatedDate]         DATETIME         NOT NULL,
    [ModifiedBy]          INT              NULL,
    [ModifiedDate]        DATETIME         NULL,
    CONSTRAINT [PK_Provider] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Provider_Provider] FOREIGN KEY ([fk_ParentProviderID]) REFERENCES [dbo].[Provider] ([ID])
);

